name: Run tests

on: [push, pull_request]

jobs:
  test:
    env:
      PYTHON: ""
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.4', '1']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("ChemistryFeaturization")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'a